### ISSUE TITLE
Developer may integrate Compensated with their existing Rails App without wrapping it in custom model classes

### ISSUE THREAD

**Issue by zspencer** [zinc-collective/compensated#52]
Now that we've gotten 3~4 implementations within Rails apps; it seems like a reasonable next step will be to create [a Rails Engine](https://guides.rubyonrails.org/engines.html) that encourages a domain model.

## Suggested Steps:

- [x] Sprout a `compensated-rails` gem that is a sibling to `compensated-ruby`; 
- [ ] Ensure that `compensated-rails` test suite gets executed across Ruby versions within CI
- [ ] Ensure that the `compensated-rails` test suite gets executed across Rails versions within CI
- [ ] Create a `Compensated::Rails::Event` [resource and supporting migrations](https://guides.rubyonrails.org/engines.html#generating-an-article-resource)
- [ ] Create `Compensated::Rails::Customer` and `Compensated::Rails::PaymentProfile` resources so that we can associate events with the payments provider and the customer the events relate to.
- [ ] Update the [compensated-rails-5-example](https://github.com/zinc-collective/compensated/tree/0.X/examples/compensated-rails-5) to use the engine

I'm comfortable merging this into `0.X` in small steps _or_ one big PR; so long as it's not making significant changes to the `compensated-ruby` directory.

**Comment by user512** [comment]
This is our understanding between `compensated-ruby` & `compensated-rails`.
1. `compensated-rails` will depend on `compensated-ruby`.
1. `compensated-ruby` will be responsible for core logic, including parsing webhook event.
1. `compensated-rails` will be generating required tables and provide reader methods.
1. Existing users of `compensated-ruby` will be able to keep using that gem can expect further future code improvement without needed to transition to `compensated-rails`.

@zspencer Does these align with what you were thinking?

**Comment by zspencer** [comment]
Yep! this matches what I was imagining perfectly!
