### ISSUE TITLE
Client developer may use packaged fixtures when integrating Compensated

### ISSUE THREAD

**Issue by jalcine** [zinc-collective/compensated#68]
Currently, the core `compensated` library holds a lot of useful code around the fixtures for testing responses from Stripe and Apple Pay. Moving them into a separate library (ideally `compensated-spec`) will allow any other Compensated gem to use them and share changes upstream. This can be also be used by other projects that want to test how Compensated responds to particular events.

### Feature Definition

```features/spec-fixtures.feature
Feature: Spec Fixtures
  In order to more easily test how payment processor events will impact my system
  As a Client Developer
  I want to be able to apply payment gateway event fixtures in my automated test suite
```

### This Issue May Be Closed When

- [x] There is a `compensated-spec` module that is packaged as it's own gem.
- [ ] _One_ Consuming project uses `compensated-spec` to test their integration.
- [ ] `compensated-ruby` uses `compensated-spec` for all its fixtures 
  - [x] `spec/stripe` - https://github.com/zinc-collective/compensated/pull/83/
  - [x] `spec/apple_iap` - https://github.com/zinc-collective/compensated/pull/84
  - [ ] `spec/gumroad` 
- [x] `compensated-proxy` uses `compensated-spec` for all its fixtures - https://github.com/zinc-collective/compensated/pull/83/
- [ ] `compensated-rails` uses `compensated-spec` for all its fixtures  
- [ ] We have released the new gem in a release candidate.
- [ ] We have updated the `CHANGELOG.md` to indicate this new feature.
- [ ] We have written a guide to testing your Compensated integration using `compensated-spec` and published it at `www.zinc.coop/compensated/testing-your-integration`
- [ ] We have announced the new library.

**Comment by zspencer** [comment]
@jalcine - nice! I've updated the issue body to add some acceptance criteria and sprout a feature definition.

I think this is a pretty big chunk of work (likely exceeding our "4 hour timebox") so I've added the epic label. 

As a thank you for taking the time to put this issue together, [I've transferred you 20 points from my personal patronage account balance](https://airtable.com/tblndyi9VR3shxtmS/viwxgldsOPhzLxfpV/reco8dqi064vscGK4). These points are worthless for now, but may be redeemed for a share of the profits generated by Zinc (you know, once we have them :)).

**Comment by zspencer** [comment]
@jalcine - Do you think this is kind of where you want this to be headed: https://github.com/zinc-collective/compensated/pull/72

The goal here is to make it possible for you to generate events from any of the payment processors we support and throw them at a compensated-proxy or a ruby project that is using the compensated gem so you can programmatically test scenarios without having to assemble the fixtures yourself.

Thoughts?

**Comment by jalcine** [comment]
> @jalcine - Do you think this is kind of where you want this to be headed: #72
> 
> The goal here is to make it possible for you to generate events from any of the payment processors we support and throw them at a compensated-proxy or a ruby project that is using the compensated gem so you can programmatically test scenarios without having to assemble the fixtures yourself.

This satisfies the needs I'll have when wanting to incorporate Compensated!
